###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light, dark, grey, auto.

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# Use this site to generate the secret: https://www.grc.com/passwords.htm
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://www.google.com/ #where to redirect for a non-existent URL

log:
  level: debug # warn

server:
  host: 0.0.0.0
  port: 9091 #PORT ili 9091?
 path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE

totp:
  issuer: CHANGE-DOMAINNAME #yourdomain.com - your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where authorized users are stored
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "CHANGE-SUBDOMAIN.CHANGE-DOMAINNAME" #This should be your authentication URL
      policy: bypass
    #- domain: "CHANGE-DOMAINNAME" #example domain to protect
    #  policy: one_factor
    - domain:
        - "pass.CHANGE-DOMAINNAME" #example subdomain to protect
      policy: one_factor
    - domain:
        - "cloud.CHANGE-DOMAINNAME" #example subdomain to protect
      policy: one_factor
    #- domain: "*.CHANGE-DOMAINNAME" #example to protect all subdomains under top-level domain
    #  policy: one_factor
      #add or remove additional subdomains as necessary. currenlty only supports ONE top-level domain
      #any time you add a new subdomain, you will need to restart the Authelia container to recognize the new settings/rules

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Use this site to generate the secret: https://www.grc.com/passwords.htm
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: CHANGE-DOMAINNAME # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m #120
  ban_time: 12h #300

storage:
# For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
#  local:
#    path: /config/db.sqlite3
#  encryption_key: generate_a_random_string_of_more_than_twenty_chars #use docker secret file instead
  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
    host: authelia-db
    port: 3306
    database: authelia-db
    username: auth-dbuser
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    # password: use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE

notifier:
  disable_startup_check: true #true/false
  smtp:
    username: CHANGE-EMAIL #your email address
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port  #465?
    sender: CHANGE-EMAIL

    identifier: localhost
    subject: "[Authelia] {title}" #email subject
    startup_check_address: CHANGE-EMAIL
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2

  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
#  filesystem:
#    filename: /tmp/authelia/notification.txt
...
