version: "3.9"

networks:
  auth:
    name: auth
    driver: bridge

secrets:
  authelia_jwt_secret:
    file: ./secrets/authelia_jwt_secret

  authelia_session_secret:
    file: ./secrets/authelia_session_secret

  authelia_storage_encryption_key:
    file: ./secrets/authelia_storage_encryption_key

  authelia_notifier_smtp_password:
    file: ./secrets/authelia_notifier_smtp_password

  authelia_storage_mysql_password:
    file: ./secrets/authelia_storage_mysql_password
    
  mysql_root_password:
    file: ./secrets/mysql_root_password
    
services:

  # MariaDB - The open source relational database.
  authelia-db:
    image: mariadb:latest
    #command: --skip-innodb-read-only-compressed	# Potrebno za NextCloud, Authelia?
    container_name: authelia-db # change for multiple instances
    restart: always

    networks:
      - auth

    secrets: 
      - mysql_root_password
      - authelia_storage_mysql_password

    volumes:
      - ./authelia-db-data:/var/lib/mysql

    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=authelia-db
      - MYSQL_USER=auth-dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password

  # Redis - Key-value Store
  redis:
    image: redis:alpine
    container_name: redis
    entrypoint: redis-server --appendonly yes  --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: always

    networks:
      - auth

    volumes:
      - ./redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - $REDISPORT:6379

    environment:
      - TZ=$TZ
      - REDIS_PASSWORD=$REDIS_PASSWORD

  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: authelia
    # Check this before upgrading: https://github.com/authelia/authelia/blob/master/BREAKING.md
    image: authelia/authelia:latest
    restart: always
    healthcheck:
      disable: true

    depends_on:
      - authelia-db

    networks:
      - auth

    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_storage_encryption_key

    ports:
      - $AUTHPORT:9091

    volumes:
      - ./:/config

    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key

  # Watchtower - automating Docker container base image updates.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always

    networks:
      - auth

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=$TZ
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 30 5 * * * # Everyday at 5:30
