version: "3.9"

networks:
  auth:
    name: auth
    driver: bridge

secrets:
  authelia_jwt_secret:
    file: ./secrets/authelia_jwt_secret

  authelia_session_secret:
    file: ./secrets/authelia_session_secret

  authelia_storage_encryption_key:
    file: ./secrets/authelia_storage_encryption_key

  authelia_notifier_smtp_password:
    file: ./secrets/authelia_notifier_smtp_password

  authelia_storage_mysql_password:
    file: ./secrets/authelia_storage_mysql_password
    
  authelia_session_redis_password_file:
    file: ./secrets/authelia_session_redis_password_file

  mysql_root_password:
    file: ./secrets/mysql_root_password
    
services:

  # MariaDB
  authelia-db:
    image: mariadb:latest
    #command: --skip-innodb-read-only-compressed	# Potrebno za NextCloud, Authelia?
    container_name: authelia-db # change for multiple instances
    restart: always

    networks:
      - auth

    secrets: 
      - mysql_root_password
      - authelia_storage_mysql_password

    volumes:
      - ./authelia-db-data:/var/lib/mysql

    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=authelia-db
      - MYSQL_USER=auth-dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

    networks:
      - auth

    volumes:
      - ./redis:/data

    ports:
      - $REDISPORT:6379

    environment:
      - TZ=$TZ
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password_file

  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: authelia
    # Check this before upgrading: https://github.com/authelia/authelia/blob/master/BREAKING.md
    image: authelia/authelia:latest
    restart: always
#    healthcheck:
#      disable: true

    depends_on:
      - authelia-db
      - redis

    networks:
      - auth

    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_storage_encryption_key
      - authelia_session_redis_password_file

    ports:
      - $AUTHPORT:9091

    volumes:
      - ./:/config

    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password_file
